### ISSUE TITLE
no-weapons maps needed for initial start

### ISSUE THREAD

**Issue by PathosEthosLogos** [Redix/teeworlds#6]
When a no-weapons FastCap server starts up for the first time, since it doesn't have no-weapons maps under the _maps_ directory, the server cannot be started. For example, I set this in the configs:

sv_map ctf2-no-weapons

Since ctf2-no-weapons doesn't exist, the server refuses to boot.

**Comment by Redix** [comment]
To make the server download the no-weapons maps you can set the gametype to _fastcap-no-weapons_ and use a map that already exists on your disk. Since the server checks if the current map is in the maplist for the selected gametype, no runs will be sent to the website until you switch to a no-weapons map.

In general when you set up a new server, use some dm or ctf map and set the intended gametype. It will download the needed maps and you can switch to a valid map as soon as the first maps have been downloaded. The server makes sure that only valid runs are submitted to the website. It checks if the gametype, settings and tunings are correct for the current map.

With the _wa_map_types_ variable you can filter the maps that you want to download (and show in the votes). For example if you only want to offer long race maps instead of all race maps, set _wa_map_types_ to _race long_. You only have to make sure that _wa_map_types_ contains the gametype you set, otherwise _wa_map_types_ will be ignored. If you want to offer all maps for a gametype, _wa_map_types_ can be left blank.

When a map contains _no-weapons_ in its name and the gametype is _fastcap_, it will be forced to _fastcap-no-weapons_.

**Examples:**

- All Race maps:
```
sv_gametype race
wa_map_types race (or leave it blank)
```

- Long Race maps:
```
sv_gametype race
wa_map_types race long
```

- All FastCap maps:
```
sv_gametype fastcap
wa_map_types fastcap (or leave it blank)
```

- All FastCap no-weapons maps:
```
sv_gametype fastcap-no-weapons
wa_map_types fastcap-no-weapons (or leave it blank)
```

- Short FastCap maps (uncommon but should work):
```
sv_gametype fastcap
wa_map_types fastcap short
```

- Wrong config:
```
sv_gametype race
wa_map_types short (will be ignored since it does not contain "race")
```
